### ISSUE TITLE
多节点怎样保证job消费redis的订阅重复消费的问题

### ISSUE THREAD

**Issue by kuainiao** [poembro/goim-demo#1]
多节点怎样保证job消费redis的订阅重复消费的问题
// Subscribe
func (j *Job) ConsumeRedis() error {
	ctx := context.TODO()
	pubsub := j.redis.Subscribe(ctx, j.c.Kafka.Topic)
	defer pubsub.Close()
	// 在发布任何内容之前，请等待确认已创建订阅
	_, err := pubsub.Receive(ctx)
	if err != nil {
		panic(err)
	}

	ch := pubsub.Channel()
	for {
		select {
		case msg, ok := <-ch:
			if !ok {
				return nil
			}
			if len(msg.Payload) <= 0 {
				continue
			}

			pushMsg := new(pb.PushMsg)
			if err := proto.Unmarshal([]byte(msg.Payload), pushMsg); err != nil {
				log.Errorf("proto.Unmarshal(%v) error(%v)", msg, err)
				return err
			}

			log.Infoln("Subscribe message:", pushMsg)
			if err := j.Push(context.Background(), pushMsg); err != nil {
				log.Errorf("j.Push(%v) error(%v)", pushMsg, err)
				return err
			}
		}
	}

}

**Comment by poembro** [comment]
如果要用redis 部署多节点job,这里可能要将(publish/subscribe) 改成  (lpush/brpop)

**Comment by kuainiao** [comment]
邮件已收到，谢谢！谢云飞
